#!/bin/bash

function parse_property {
    echo "$(cut -d "=" -f2- <<< "$(grep -w "$1" settings.properties)")"
}

WINEPREFIX="$(parse_property "WINEPREFIX")"
WINE_BIN="$(parse_property "WINE_BIN")"
WRAPPER_COMMAND="$(parse_property "WRAPPER_COMMAND")"

if ! [ -e "$WINE_BIN" ]; then
    echo "Invalid wine bin; wine binary not found."
    exit 0
fi

export WINEARCH=win32
export WINEPREFIX
export WINE_BIN
export WRAPPER_COMMAND

echo "Loaded Wine prefix - $WINEPREFIX"
echo "Loaded Wine binary - $WINE_BIN"
echo "Loaded wrapper command - $WRAPPER_COMMAND"
