#!/bin/bash
set -e

OS_RELEASE_FILES=("/etc/os-release" "/usr/lib/os-release")

for release in ${OS_RELEASE_FILES[@]} ; do
    if [[ ! -e "$release" ]]; then
        continue
    fi
    DISTRO=$(sed -rn 's/^NAME=(.+)/\1/p' "$release" | sed 's/"//g')
done

escape_code() {
    echo "\033[$1m"
}

SUCCESS_PREFIX="$(escape_code "0;32")✓$(escape_code 0)"
QUESTION_PREFIX="$(escape_code "0;36")❓$(escape_code 0)"
ERROR_PREFIX="$(escape_code "0;31")❌$(escape_code 0)"

load_properties() {
    . ./variables.exports
    echo -e "$SUCCESS_PREFIX Loaded properties on $(uname -om)."
}

dependencies() {
    function join {
        local IFS="$1"
        shift
        echo "$*"
    }

    declare -a MISSING_DEPENDENCIES

    type winetricks &> /dev/null || MISSING_DEPENDENCIES+=("winetricks")
    [ ! -f "$WINE_BIN" ] && MISSING_DEPENDENCIES+=("wine")

    if (( ${#MISSING_DEPENDENCIES[@]} )); then
        read -p "$(echo -e "${QUESTION_PREFIX}We found ${#MISSING_DEPENDENCIES[@]} missing dependencies. You want to install automatically? (y/N): ")" prompt
        if [[ $prompt =~ [yY](es)* ]]; then
            local all=$(join " " ${MISSING_DEPENDENCIES[@]})
            case $DISTRO in
                "Arch Linux"|"Manjaro Linux")
                    INSTALL_STATEMENT="pacman -S" ;;
                *"buntu"|"Linux Mint"|"Debian*"|"Zorin OS"|"Pop!_OS"|"elementary OS"|"KDE neon")
                    INSTALL_STATEMENT="apt install" ;;
                "Fedora")
                    INSTALL_STATEMENT="dnf install" ;;
                "openSUSE"*)
                    INSTALL_STATEMENT="zypper install" ;;
                "Solus")
                    INSTALL_STATEMENT="eopkg it" ;;
                *)
                    echo -e "$ERROR_PREFIX Could not install dependencies automatically. Missing: $all"
                    exit -1 ;;
            esac
            sudo $INSTALL_STATEMENT $all
        fi
    fi
}

launch() {
    if ! [ -e "./_installer.exe" ]; then
        wget -O _installer.exe "https://m1.ppy.sh/r/osu!install.exe"
    fi

    # Create Wine prefix and execute installer + setup required dependencies.
    if ! [ -d "$WINEPREFIX" ]; then
        winetricks --unattended --force dotnet48 gdiplus vlgothic cjkfonts
    fi

    "$WINE_BIN" "$PWD/_installer.exe"
}

if [ -x "$DISTRO" ]; then
    echo  -e "$ERROR_PREFIX Could not detect your operational system. You will be not able to install dependencies through this script."
fi

load_properties
dependencies
launch
