#!/bin/bash

function parse_property {
    echo "$(cut -d "=" -f2- <<< "$(grep -w "$1=" settings.properties)")"
}

WINEPREFIX="$(parse_property "WINEPREFIX")"
WINE_BIN="$(parse_property "WINE_BIN")"
DXVK_STATE_CACHE_PATH="$(parse_property "DXVK_CACHE_PATH")"
GENSHIN_IMPACT_VERSION="$(parse_property "GENSHIN_IMPACT_VERSION")"

if ! [ -e "$WINE_BIN" ]; then
    echo "Invalid wine bin; wine binary not found."
    exit 0
fi

export WINEPREFIX
export WINE_BIN
export DXVK_STATE_CACHE_PATH
export GENSHIN_IMPACT_VERSION
export DXVK_ASYNC=1

echo "Loaded Wine prefix - $WINEPREFIX"
echo "Loaded Wine binary - $WINE_BIN"
echo "Loaded DXVK Cache - $DXVK_STATE_CACHE_PATH"
echo "Loaded asynchronous DXVK shader compiling"
