#!/bin/bash

function parse_property {
    echo "$(cut -d "=" -f2- <<< "$(grep -w "$1" settings.properties)")"
}

export WINEPREFIX="$(parse_property "WINEPREFIX")"
export WINE_BIN="$(parse_property "WINE_BIN")"
export DXVK_STATE_CACHE_PATH="$(parse_property "DXVK_CACHE_PATH")"
export GENSHIN_IMPACT_VERSION="$(parse_property "GENSHIN_IMPACT_VERSION")"
export WRAPPER_COMMAND="$(parse_property "WRAPPER_COMMAND")"
export DXVK_ASYNC="$(parse_property "DXVK_ASYNC")"
export WINEESYNC="$(parse_property "WINEESYNC")"
export WINEFSYNC="$(parse_property "WINEFSYNC")"

if ! [ -e "$WINE_BIN" ]; then
    echo "Invalid wine bin; wine binary not found."
    exit 0
fi

echo "Loaded Wine prefix - $WINEPREFIX"
echo "Loaded Wine binary - $WINE_BIN"
echo "Loaded DXVK Cache - $DXVK_STATE_CACHE_PATH"
echo "Loaded wrapper command - $WRAPPER_COMMAND"
if [ "$WINEESYNC" == "1" ]; then
    echo "Loaded Wine ESync"
fi
if [ "$WINEFSYNC" == "1" ]; then
    echo "Loaded Wine FSync"
fi
if [ "$DXVK_ASYNC" == "1" ]; then
    echo "Loaded asynchronous DXVK shader compiling"
fi
